kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: com-os
  labels:
    app: com-os
spec:
  replicas: 1
  selector:
    matchLabels:
      app: com-os
  template:
    metadata:
      labels:
        app: com-os
    spec:
      hostNetwork: true
      nodeSelector:
        node3: worker3
      containers:
      - name: com-os
        image: registry.cn-shanghai.aliyuncs.com/qianjian/com-os
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/laser/config/paas/laser/
          name: com-os-cache
        - mountPath: /usr/local/tomcat/bin/catalina.sh
          name: com-os-catalina
        - mountPath: /data/laser/config/paas/com-os/laser.properties
          name: com-os-config
          subPath: laser.properties
        - mountPath: /usr/local/tomcat/conf/server.xml
          name: com-os-server
        - mountPath: /usr/local/tomcat/conf/context.xml
          name: com-os-context
        - mountPath: /data/logs/laser/paas/com-os
          name: com-os-log
        - mountPath: /usr/local/tomcat/logs
          name: com-os-catalinalog
        - mountPath: /usr/local/tomcat/lib/mysql-connector-java-5.1.32.jar
          name: com-os-mysql-lib
        ports:
        - containerPort: 8015
        readinessProbe:
          tcpSocket:
            port: 8015
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8015
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: com-os-cache
        configMap:
          name: cache.properties
      - name: com-os-catalina
        hostPath:
          path: /data/project/paas/java/com/com-os/catalina.sh
      - name: com-os-config
        configMap:
          name: com-os.properties
      - name: com-os-server
        hostPath:
          path: /data/project/paas/java/com/com-os/server.xml
      - name: com-os-context
        hostPath:
          path: /data/project/paas/java/com/context.xml
      - name: com-os-log
        hostPath:
          path: /log/paas/java/com-os/app/
      - name: com-os-catalinalog
        hostPath:
          path: /log/paas/java/com-os/tomcat/
      - name: com-os-mysql-lib
        hostPath:
          path: /data/project/paas/java/com/mysql-connector-java-5.1.32.jar
      imagePullSecrets:
      - name: regsecret

---
apiVersion: v1
kind: Service
metadata:
  name: com-os
spec:
  ports:
    - port: 8015
      protocol: TCP
      nodePort: 38015
  clusterIP: 10.68.21.15
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort
  selector:
    app: com-os
