kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: controller-basic
  labels:
    app: controller-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-basic
  template:
    metadata:
      labels:
        app: controller-basic
    spec:
      hostNetwork: true
      nodeSelector:
        node3: worker3
      containers:
      - name: controller-basic
        image: registry.cn-shanghai.aliyuncs.com/qianjian/controller-basic
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/laser/config/paas/laser/
          name: controller-basic-cache
        - mountPath: /usr/local/tomcat/bin/catalina.sh
          name: controller-basic-catalina
        - mountPath: /data/laser/config/paas/controller-basic/laser.properties
          name: controller-basic-config
          subPath: laser.properties
        - mountPath: /usr/local/tomcat/conf/server.xml
          name: controller-basic-server
        - mountPath: /usr/local/tomcat/conf/context.xml
          name: controller-basic-context
        - mountPath: /data/logs/laser/paas/controller-basic
          name: controller-basic-log
        - mountPath: /usr/local/tomcat/logs
          name: controller-basic-catalinalog
        - mountPath: /usr/local/tomcat/lib/mysql-connector-java-5.1.32.jar
          name: controller-basic-mysql-lib
        ports:
        - containerPort: 8025
        readinessProbe:
          tcpSocket:
            port: 8025
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8025
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: controller-basic-cache
        configMap:
          name: cache.properties
      - name: controller-basic-catalina
        hostPath:
          path: /data/project/paas/java/com/controller-basic/catalina.sh
      - name: controller-basic-config
        configMap:
          name: controller-basic.properties
      - name: controller-basic-server
        hostPath:
          path: /data/project/paas/java/com/controller-basic/server.xml
      - name: controller-basic-context
        hostPath:
          path: /data/project/paas/java/com/context.xml
      - name: controller-basic-log
        hostPath:
          path: /log/paas/java/controller-basic/app/
      - name: controller-basic-catalinalog
        hostPath:
          path: /log/paas/java/controller-basic/tomcat/
      - name: controller-basic-mysql-lib
        hostPath:
          path: /data/project/paas/java/com/mysql-connector-java-5.1.32.jar
      imagePullSecrets:
      - name: regsecret

---
apiVersion: v1
kind: Service
metadata:
  name: controller-basic
spec:
  ports:
    - port: 8025
      protocol: TCP
      nodePort: 38025
  clusterIP: 10.68.21.25
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort
  selector:
    app: controller-basic
