kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: nginx-lua
  labels:
    app: nginx-lua
spec:
  selector:
    matchLabels:
      app: nginx-lua
  template:
    metadata:
      labels:
        app: nginx-lua
    spec:
      nodeSelector:
        node: worker
      containers:
      - name: nginx-lua
        image: registry.cn-shanghai.aliyuncs.com/qianjian/nginx-lua
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/local/nginx/logs
          name: nginx-lua-log
        - mountPath: /usr/local/nginx/conf/vhosts
          name: nginx-lua-conf
        - mountPath: /usr/local/nginx/conf/nginx.conf
          name: nginx-conf
        ports:
        - containerPort: 80
          hostPort: 80
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 80
#            scheme: HTTP
#          timeoutSeconds: 5
#          initialDelaySeconds: 300
#          periodSeconds: 15 
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 80
#            scheme: HTTP
#          timeoutSeconds: 5
#          initialDelaySeconds: 300
#          periodSeconds: 15
      volumes:
      - name: nginx-lua-log
        hostPath:
          path: /data/project/nginx-lua/logs
      - name: nginx-lua-conf
        hostPath:
          path: /data/project/nginx-lua/vhosts
      - name: nginx-conf
        hostPath:
          path: /data/project/nginx-lua/nginx.conf
      imagePullSecrets:
      - name: regsecret

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lua
spec:
  ports:
    - port: 80
      nodePort: 80
      protocol: TCP
  type: NodePort
  clusterIP: 10.68.0.14
  selector:
    app: nginx-lua
